id: I2B02A144
initial_creation_type: ebook
source_metadata:
  id: RDI-SS-28
  title: དཔལ་འཇིག་རྟེན་དབང་ཕྱུག་གི་ཆོ་གའི་ཟིན་བྲིས་རབ་གསལ་ཐར་པའི་ལམ་ཆེན་ལས་བདག་བསྐྱེད་ཀྱི་དཀའ་བའི་གནད་རྣམས་བཀྲོལ་བ་དོན་འགྲེལ་ཉི་མའི་འོད
  author: མཛད་པ་པོ། མཁས་གྲུབ་རཱ་ག་ཨ་སྱ།
  authors: &id001
  - མཛད་པ་པོ། མཁས་གྲུབ་རཱ་ག་ཨ་སྱ།
  sku: RDI-SS-28
  cover: RDI-SS-28.jpg
  volume: {}
  title_source: epub:dc:title:ambiguous-layer
ebook_metadata:
  title: དཔལ་འཇིག་རྟེན་དབང་ཕྱུག་གི་ཆོ་གའི་ཟིན་བྲིས་རབ་གསལ་ཐར་པའི་ལམ་ཆེན་ལས་བདག་བསྐྱེད་ཀྱི་དཀའ་བའི་གནད་རྣམས་བཀྲོལ་བ་དོན་འགྲེལ་ཉི་མའི་འོད
  authors: *id001
  sku: RDI-SS-28
  cover: RDI-SS-28.jpg
layers:
- Author
- BookNumber
- BookTitle
- Chapter
- Citation
- Commentary
- Sabche
